// <auto-generated />
using System;
using FootballIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballIQ.Infrastructure.Migrations
{
    [DbContext(typeof(FootballIQDbContext))]
    [Migration("20260622164236_AddPlayerPositionCounts")]
    partial class AddPlayerPositionCounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballIQ.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatsBombTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatsBombTeamId")
                        .IsUnique();

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.IngestionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatsBombMatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatsBombMatchId")
                        .IsUnique();

                    b.ToTable("ingestion_log", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwayClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("StatsBombMatchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.HasIndex("StatsBombMatchId")
                        .IsUnique();

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredFoot")
                        .HasColumnType("text");

                    b.Property<int>("StatsBombPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StatsBombPlayerId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.PlayerPositionTally", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Position")
                        .IsUnique();

                    b.ToTable("player_position_counts", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer");

                    b.Property<double>("ExpectedAssists")
                        .HasColumnType("double precision");

                    b.Property<double>("ExpectedGoals")
                        .HasColumnType("double precision");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("MinutesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("PassesAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("PassesCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pressures")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_season_stats", (string)null);
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.Match", b =>
                {
                    b.HasOne("FootballIQ.Domain.Entities.Club", null)
                        .WithMany()
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballIQ.Domain.Entities.Club", null)
                        .WithMany()
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.PlayerPositionTally", b =>
                {
                    b.HasOne("FootballIQ.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.PlayerSeasonStats", b =>
                {
                    b.HasOne("FootballIQ.Domain.Entities.Club", "Club")
                        .WithMany("SeasonStats")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballIQ.Domain.Entities.Player", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.Club", b =>
                {
                    b.Navigation("SeasonStats");
                });

            modelBuilder.Entity("FootballIQ.Domain.Entities.Player", b =>
                {
                    b.Navigation("SeasonStats");
                });
#pragma warning restore 612, 618
        }
    }
}
